### ISSUE TITLE
The problem of network input dimension

### ISSUE THREAD

**Issue by SimonZhong22** [wherzberg/GN4IP#1]
Hello, I have a problem when reading your paper (**Domain independent post-processing with graph U-nets: applications to electrical impedance tomographic imaging**):

In Section 4.1, you implement post-processing of 3D image using the GNN-TV1 (trained on the 2D data), and the input of GNN-TV1 $x^{in}$ is 1 × N dimension. 

In Section 2.3.3, you point out that the mesh element number for the training data is 3984, which means that the GNN-TV1 input $x^{in}$ has dimension of 1 × 3984.  
{... _and the reconstruction mesh was the same as the one used for the experimental KIT4 datasets (3984 elements)._ ...}

However, the 3D box has 85699 elements, which does not match the inputs of the trained network GNN-TV1. 
{ ..._The computational mesh for the 3D box tank shown in figure 5 had 85 699 elements and 18 569 nodes. Solutions were computed on the elements, using linear basis functions, and thus the associated graph had 85 699 nodes._ ...}

Can you give further details on this? 

Looking forward to hearing from you. Thanks.

**Comment by wherzberg** [comment]
Those numbers and statements are accurate. One of the most significant advantages to using graph neural networks (GNN) in this application (as opposed to CNN or a dense multilayer perceptron) is that a single network can allow for input graphs with varying numbers of nodes. It may help to review Equation 1 for a graph convolutional layer (and also Kipf and Welling, 2016). An important note is that the size of the weight matrix for a graph convolutional layer is not dependent on the number of nodes in the input graph N. All of the other layers in the proposed network also allow for input graphs with different numbers of nodes and different adjacency matrices.
Hope that helps and please reply if you have further questions!
